- name: Discord Webhook Notify
  uses: rjstone/discord-webhook-notify@v1.0.1
  with:
    # Discord webhook URL. Should be stored in a secret and inserted as a context expression.
    webhookUrl: # https://discordapp.com/api/webhooks/653112928987381800/3pMPpBJa26vn-ynbdx4oZmDTsA0dmQP628rt_g4ce5q70LCimKSddqc_eakv8rGJkTok
    # Severity level - info, warn, or error
    severity: # optional, default is error
    # Embed notification message. Use context expressions and environment variables to provide information. Default provides branch and user info.
    description: # optional
    # Additional text after the notification message in case you want to retain the default message.
    details: # optional
    # Footer for the embed. Defaults to severity.
    footer: # optional
    # Text to be sent as normal text above the embed. Use context expressions and environment variables to provide information.
    text: # optional
    # Username to display in discord.
    username: # optional
    # Notification color in the form poundsign rrggbb (hex). Default determined by severity.
    color: # optional
    # URL to png of discord avatar to use. Default is the GitHub monochrome mark cat logo.
    avatarUrl: # optional
